[project]
name = "langgraph-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "langchain[anthropic]>=1.0.3",
    "langgraph>=1.0.2",
    "python-dotenv>=1.2.1",
]
